imports:
    - { resource: service/legacy_aliases.yml }
    - { resource: service/front.yml }
    - { resource: service/loader.yml }

services:
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Exception,Api}'

    app.relations.cache_provider:
        class: Doctrine\Common\Cache\ArrayCache

    app.brickset.cache_provider:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments: ["%kernel.cache_dir%/brickset", ".cache.php"]

    AppBundle\Api\Client\Brickset\BricksetClient:
        arguments:
            $apiKey: '%brickset_apikey%'

    AppBundle\Api\Client\Rebrickable\RebrickableClient:
        arguments:
            $apiKey: '%rebrickable_apikey%'

    AppBundle\Api\Manager\RebrickableManager: ~

    AppBundle\Api\Manager\BricksetManager:
        arguments:
           $cache: '@app.brickset.cache_provider'

    FrontBundle\Form\Search\SetSearchType:
        arguments:
            $showOnlyThemesContainingSets: %app.show_only_themes_containing_sets%

    # Filesystem

    League\Flysystem\FilesystemInterface:
        alias: oneup_flysystem.media_filesystem


    # ElasticSearch

    #FOS\ElasticaBundle\Manager\RepositoryManagerInterface:
    #    alias: fos_elastica.repository_manager

    AppBundle\Service\SearchService:
        arguments:
    #        - '@fos_elastica.manager'
            - '@doctrine.orm.entity_manager'